baseURL: https://anecdatos.com/
languageCode: es-es
defaultContentLanguage: es
title: Anecdatos
theme: toha-bpi

taxonomies:
  author: authors
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - AMP

languages:
  es:
    languageName: Español
    weight: 1
    permalinks:
      authors: /autores/:slug
      categories: /categorias/:slug

privacy:
  twitter:
    disable: false
    enableDNT: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

params:
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/main-logo.png
    favicon: /favicon.ico
  gitRepo: https://github.com/chusopr/anecdatos
  gitBranch: website
  enableBlogPost: true
  postsPerPage: 15
  enableTOC: false
  enableSearch: true
  recentPostsNum: 6
  footer: false
  splash: false
  hero_in_post_page: false
  newsletter:
    enable: false
  share:
    facebook: true
    mastodon: 'En @anecdatos@mstdn.io: "%s" %s'
    twitter:
      message: 'En @anecdatos: "%s" %s %s'
      handle: anecdatos
